version: "3.9"
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: hushreg
      LANG: en_US.utf8
      LC_ALL: en_US.utf8
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql_models/seed.sql:/docker-entrypoint-initdb.d/seed.sql
    expose:
      - "5435"

  registry:
    build: .
    environment:
      DATABASE_URL: postgres://postgres:dev@db:5432/hushreg
      HEALTH_TIMEOUT_MS: "3000"
    depends_on: [db]
    ports: ["8081:8080"]

volumes:
  postgres_data:
